# Generated by Django 6.0.6 on 2026-06-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('price_sample_count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='route_fuels_lat_9ace7a_idx'), models.Index(fields=['avg_price'], name='route_fuels_avg_pri_242ab5_idx')],
            },
        ),
    ]
